// One-time seed script — run with: npm run seed:guides
// Re-running is safe; upsert won't duplicate rows.
import sequelize from '../config/database.js'
import Guide from '../models/Guide.js'

const guides = [
  {
    slug: 'canada', title: 'Canadian Grand Prix', country: 'Canada', city: 'Montreal',
    circuit: 'Circuit Gilles Villeneuve',
    coordinates: { lat: 45.5006, lng: -73.5228 },
    weather: { location: 'Montreal, Canada' },
    circuitInfo: { laps: 70, length_km: 4.361, drs_zones: 3, first_gp: 1978 },
    guideSections: {
      beforeRace: {
        title: 'Before the Race',
        description: 'Montreal welcomes the Grand Prix as the start of summer, so the atmosphere spreads far beyond the island and Circuit Gilles-Villeneuve itself. The best part of the trip here is that you can combine the French-Canadian city rhythm, excellent food, and very easy access to the track all in the same day.',
        tips: [
          'Walk through Old Montreal from Rue Saint-Paul to Vieux-Port a day or two before the main crowds arrive, because this part of the city feels best early in the morning before the weekend fully comes alive.',
          'If you arrive in the city early enough before the island becomes fully restricted, rent a BIXI bike and ride a lap around Circuit Gilles-Villeneuve in Parc Jean-Drapeau to understand how flat and fast the track really is.',
          'Book dinner on Peel Street, Crescent Street, or in Griffintown no later than Wednesday or Thursday, because that is where most of the pre-race city energy gathers.',
          'Go to Parc Jean-Drapeau and Espace 67 the day before the race so you can see in advance how people flow toward the Concorde and Cosmos bridges.',
          'If you want a better local city atmosphere than the official promotional zones, spend a few hours in Plateau between Avenue du Mont-Royal and Rue Saint-Denis, where the vibe is less touristy and much livelier.',
          'Buy water, snacks, and small essentials downtown or in Longueuil before entering the island, because queues and prices around the track become noticeably worse from Thursday afternoon onward.',
        ],
      },
      duringRace: {
        title: 'During the Race',
        description: 'On race day Montreal feels like the entire city is pouring onto Île Notre-Dame, but the logistics are actually fairly manageable if you follow the metro and bridges instead of using a car. The circuit itself offers a rare combination of stadium-style grandstands, picnic energy by the lake, and excellent viewing spots for the opening lap and heavy braking zones.',
        tips: [
          'Take the metro to Jean-Drapeau on the Yellow Line and buy a return ticket in advance at Berri-UQAM or Longueuil-Université-de-Sherbrooke, because those stations create the biggest post-race queues.',
          'If you are sitting near the Senna corner, arrive early enough to pass security calmly and catch the support categories, because this sector is one of the best for the opening lap and often for the first serious incidents.',
          'For slower technical action, aim for the L\'Épingle hairpin area, where you can really see how late the drivers brake and how aggressively they exit onto the long straight.',
          'Bring a light rain jacket and earplugs even if the city center is sunny, because the wind from the Saint Lawrence River on the island often changes the perceived temperature within an hour.',
          'If you use the southern access via Victoria Bridge, check whether your grandstand matches that entrance, because it is not valid for every sector and you do not want to discover that at the checkpoint.',
          'After the checkered flag, avoid rushing into the first metro wave and instead wait around twenty minutes on the island or walk toward Concorde Bridge if your sector allows it.',
        ],
      },
      travelAdvice: {
        title: 'Travel Advice',
        description: 'In Montreal it makes much more sense to stay near the metro than near the track, because the island itself has no practical city accommodation and you will be entering from the mainland every day anyway. The easiest bases are the ones that connect you directly to the Yellow Line or quickly to Berri-UQAM.',
        tips: [
          'The most practical neighborhoods for accommodation are Downtown, Old Montreal, and the area around Berri-UQAM, because from there you can easily access the STM network and quickly reach the Yellow Line.',
          'If you want cheaper accommodation and an easier return after the race, look at Longueuil near Longueuil-Université-de-Sherbrooke station, because you are already on the opposite end of the same line everyone uses to reach the island.',
          'Do not rely on a rental car for getting to the circuit, because there is no normal public parking for spectators on the island and you will end up farther from the action than if you had stayed on the metro.',
          'For evening outings after practice sessions, the best balance between access and atmosphere is Peel Street, Crescent Street, and Griffintown, but expect noise late into the night.',
          'If you want quieter mornings and better cafés, Plateau and Mile End are better than the hotel zone around Bell Centre, just leave yourself an extra twenty minutes to reach the metro.',
          'Pack a small shoulder bag you can comfortably carry all day, because Jean-Drapeau involves a lot of walking between the station, entrances, grandstands, and bridges even when distances look short on the map.',
        ],
      },
    },
    hotels: [
      { name: 'Hotel Bonaventure Montreal', address: '900 Rue De La Gauchetière O, Montreal, QC H5A 1E4, Canada', lat: 45.4994, lng: -73.5651 },
      { name: 'Le Centre Sheraton Montreal Hotel', address: '1201 René-Lévesque Blvd W, Montreal, QC H3B 2L7, Canada', lat: 45.4979, lng: -73.5714 },
      { name: 'Hotel Universel Montreal', address: '5000 Rue Sherbrooke E, Montreal, QC H1V 1A1, Canada', lat: 45.553, lng: -73.541 },
    ],
  },
  {
    slug: 'monaco', title: 'Monaco Grand Prix', country: 'Monaco', city: 'Monte Carlo',
    circuit: 'Circuit de Monaco',
    coordinates: { lat: 43.7347, lng: 7.4206 },
    weather: { location: 'Monaco' },
    circuitInfo: { laps: 78, length_km: 3.337, drs_zones: 1, first_gp: 1950 },
    guideSections: {
      beforeRace: {
        title: 'Before the Race',
        description: 'Monaco is a race you can truly feel beneath your feet, because the streets, crossings, tunnel, and marina are part of everyday city life long before the cars hit the circuit. The best introduction is to walk as much of the lap as possible, because only then do you realize how steep the terrain is and how every grandstand feels like a completely different city.',
        tips: [
          'Walk the entire circuit early in the morning from Sainte-Dévote through Avenue d\'Ostende to Place du Casino, then down Mirabeau and Portier to Port Hercule while the sidewalks are still manageable for photos.',
          'Have breakfast at Marché de la Condamine on Place d\'Armes and try barbagiuan or socca, because it feels far more local than the hotel terraces by the marina.',
          'Climb to Le Rocher via Rampe Major or Avenue de la Porte-Neuve before the day-trippers arrive, because the narrow streets of Monaco-Ville are most beautiful while they are still quiet.',
          'If you are staying in Nice or Menton, do a practice TER train ride to Monaco-Monte-Carlo station the day before and remember which exit works best for your grandstand.',
          'For a break from asphalt and crowds, go to Larvotto Promenade or Plage du Larvotto, where you can completely switch from race weekend mode into a Mediterranean rhythm for an hour.',
          'Buy water and small essentials in La Condamine or Fontvieille before entering the expensive marina areas, because the price difference becomes obvious immediately.',
        ],
      },
      duringRace: {
        title: 'During the Race',
        description: 'Monaco is less about walking between sectors and more about choosing one great viewing point and understanding exactly what you want to watch. Some places give you a perfect sense of speed and wall proximity, while others offer strategic views over multiple corners and the rhythm of the city breathing around the circuit.',
        tips: [
          'On race day expect a lot of stairs and vertical movement, so wear comfortable trainers with good grip instead of city shoes, because elevators and escalators do not connect every route.',
          'If you are going to Le Rocher, arrive very early with a cap and enough water, because the best viewing spots disappear long before the official program really begins.',
          'For photos and the feeling of how narrow the track is, the best sectors are around Tabac and Piscine, while Casino and Mirabeau reward precision watching more than overtaking.',
          'Use the public elevators and moving walkways between Boulevard Louis II, Rue Grimaldi, and the higher parts of Monte Carlo to save your legs for the return to the station.',
          'Do not carry bulky bags or souvenir shopping through the city, because you will constantly squeeze through barriers, stairways, and narrow pedestrian corridors.',
          'After the session, have a drink on Quai Albert Ier or Rue Caroline and wait for the first station rush to fade instead of immediately joining the densest queue.',
        ],
      },
      travelAdvice: {
        title: 'Travel Advice',
        description: 'The smartest Monaco plan is to stay outside the principality itself and rely on trains, buses, or walking, because Monaco during Grand Prix weekend punishes every travel plan built around a car. The French Riviera works in your favor here, so accommodation in neighboring towns is often both smarter and more pleasant.',
        tips: [
          'The best bases outside Monaco are Nice, Menton, Villefranche-sur-Mer, and Beausoleil, because all of them sit on the same rail corridor to Monaco-Monte-Carlo station.',
          'From Nice Côte d\'Azur Airport use Bus 80 toward Monaco if you want a direct connection without transfers instead of immediately spending heavily on taxis.',
          'If you still decide to drive, target Parking des Salines on the western entrance and then walk via Galerie des Salines and the Wurtemberg pedestrian crossing or use the free shuttle to Fontvieille.',
          'Download Monapass before your trip, because it centralizes public transport, schedules, and services you will likely need while the city transforms into a race circuit.',
          'Choose accommodation near a station or direct bus line instead of only following scenic hotel photos, because five minutes on a Monaco map can easily mean twenty minutes uphill.',
          'Travel with less luggage than usual, because the station has multiple exits and vertical connections, and a large suitcase during Grand Prix weekend becomes more punishment than comfort.',
        ],
      },
    },
    hotels: [
      { name: 'Fairmont Monte Carlo', address: '12 Av. des Spélugues, 98000 Monaco', lat: 43.74006, lng: 7.43007 },
      { name: 'Novotel Monte Carlo', address: '16 Bld Princesse Charlotte, 98000 Monaco', lat: 43.739239, lng: 7.421961 },
      { name: 'Hôtel de Paris Monte-Carlo', address: 'Place du Casino, 98000 Monaco', lat: 43.73899, lng: 7.42734 },
    ],
  },
  {
    slug: 'british', title: 'British Grand Prix', country: 'United Kingdom', city: 'Silverstone',
    circuit: 'Silverstone Circuit',
    coordinates: { lat: 52.0786, lng: -1.0169 },
    weather: { location: 'Silverstone, UK' },
    circuitInfo: { laps: 52, length_km: 5.891, drs_zones: 2, first_gp: 1950 },
    guideSections: {
      beforeRace: { title: 'Before the Race', description: 'Silverstone is not a city race weekend but a true motorsport camp surrounded by the fields of Northamptonshire, so preparation matters just as much as the race itself. Once you accept that this is a huge rural venue with lots of walking and unpredictable weather, the whole experience becomes much easier and far more enjoyable.', tips: ['Visit the Silverstone Museum before the main race weekend begins, because it gives you the best historical context for the circuit before the crowds around the grandstands become overwhelming.', 'If you are staying in Towcester or Brackley, have dinner near Watling Street or central Brackley before Thursday evening, because restaurant queues are still manageable and shopping for the weekend is much easier.', 'Buy water, breakfast supplies, and rain gear in Milton Keynes, Northampton, or Banbury before arriving at the circuit, because relying on trackside kiosks every day quickly becomes frustrating.', 'If you are camping or returning toward Silverstone Village, check the walking routes through Winterhills in advance, because that area becomes one of the main pedestrian funnels from the village and parking zones.', 'If you are taking the train to Milton Keynes Central, walk to the shuttle departure area the day before so you do not waste time searching for the correct bus line among the morning crowds.', 'Do not plan the entire weekend around only the circuit and your hotel, because the surrounding villages are calm and enjoyable during the hours when fan zones at other races are already overcrowded.'] },
      duringRace: { title: 'During the Race', description: 'Silverstone rewards people who respect its scale and avoid trying to see everything at once. The track is large enough that every sector has its own personality, from the brutal speed through Copse to the slower and more technical rhythm around Vale and Club.', tips: ['Choose one half of the circuit for the day and stay there, because trying to walk from Copse to Stowe and back usually costs more energy than the extra views are worth.', 'If you want to experience true aerodynamic speed, head toward Copse and Maggotts-Becketts, while Stowe and Vale-Club are better for watching heavy braking and exits onto the straights.', 'At Silverstone always carry both sunscreen and a waterproof layer, because the clouds and wind over the open fields can change much faster than the forecast for Northampton suggests.', 'Eat breakfast early and avoid delaying your coffee until mid-morning, because the biggest concession queues form right when the first Formula 1 activities begin.', 'If you want a smoother exit after the sessions, stay for the evening entertainment or leave your sector slightly before the main crowd, because thousands of people move through the same corridors at the same time.', 'Do not underestimate how tiring the grass banks and uneven ground become after hours of standing, so bring a seat cushion or light folding mat if you have general admission tickets.'] },
      travelAdvice: { title: 'Travel Advice', description: 'For Silverstone, accommodation is less about prestige and more about your connection to the shuttle system or easy access to the A43. Milton Keynes, Northampton, and Banbury are usually the smartest choices because they balance rail access, buses, and enough restaurants for evenings after the circuit.', tips: ['Milton Keynes is the easiest base if you are arriving from London by train, because official shuttles leave directly from Milton Keynes Central station and the routes are clearly marked.', 'Northampton, Towcester, Banbury, Oxford Parkway, Brackley, and Buckingham all offer official bus transfers to Gate 1 or Gate 19, so choose your town based on hotel price rather than map appearance.', 'If you are driving, study the approach via the A43 in advance instead of relying entirely on navigation apps, because temporary one-way systems and road closures are introduced throughout the weekend.', 'For taxis and private rides, expect drop-off and pick-up zones to be pushed toward local rail stations, which makes the train and shuttle combination more reliable than trying to drive directly to the gates.', 'If you are camping in Silverstone Village or near Woodlands, follow the marked walking routes at night and avoid cutting across dark temporary paths that may close during the event.', 'Pack sturdy shoes, layered clothing, and a power bank, because this is one of those Formula 1 weekends where you spend far more hours outdoors than you initially expect.'] },
    },
    hotels: [
      { name: 'Hilton Garden Inn Silverstone', address: 'Silverstone Circuit, Towcester NN12 8GZ, United Kingdom', lat: 52.0733, lng: -1.0147 },
      { name: 'Whittlebury Hall Hotel & Spa', address: 'Whittlebury, Towcester NN12 8WP, United Kingdom', lat: 52.08021, lng: -0.99836 },
      { name: 'Premier Inn Silverstone', address: 'Brackley Hatch, Towcester NN13 5TX, United Kingdom', lat: 52.0358, lng: -1.1472 },
    ],
  },
  {
    slug: 'belgium', title: 'Belgian Grand Prix', country: 'Belgium', city: 'Spa',
    circuit: 'Spa-Francorchamps',
    coordinates: { lat: 50.4372, lng: 5.9714 },
    weather: { location: 'Spa, Belgium' },
    circuitInfo: { laps: 44, length_km: 7.004, drs_zones: 2, first_gp: 1950 },
    guideSections: {
      beforeRace: { title: 'Before the Race', description: 'Spa-Francorchamps is more than just a circuit; it is an entire section of the Ardennes filled with small towns, forests, hills, and weather that behaves like another participant in the weekend. Before the race it is worth slowing down and experiencing the rhythm of Spa, Stavelot, or Malmedy, because that makes the main event far easier to enjoy.', tips: ['Spend a morning in Spa around Rue Royale and Parc de Sept Heures, because the town center gives a perfect contrast to the wild atmosphere you will later experience at the circuit.', 'Visit Stavelot Abbey and the Spa-Francorchamps museum before race weekend, because it helps you understand how deeply this Grand Prix is connected to local roads and regional history.', 'If you are driving, do one full practice run through Francorchamps and the nearby roads the day before so you can see where traffic bottlenecks form and how narrow the village access routes really are.', 'Buy food and drinks in Malmedy or Spa before heading to the circuit, because the selection around the track becomes far more limited once the serious crowds arrive.', 'Check Ardennes weather radars instead of only looking at forecasts from your departure city, because it is completely normal for Liège to be dry while clouds and rain already sit above Eau Rouge.', 'If you plan to use trains, simulate the transfer at Verviers-Central the evening before and remember where the bus departures are, because that removes a huge amount of stress on race morning.'] },
      duringRace: { title: 'During the Race', description: 'At Spa the terrain is half the experience, so your viewing spot determines how much you walk, climb, and move between sessions. Once you enter the circuit, it is much smarter to focus on one sector than to chase the entire lap through mud, grass, and massive distances.', tips: ['If you want to watch Eau Rouge and Raidillon, arrive very early because the best hillside viewing spots fill up quickly and later you either end up too high or too far from the fence.', 'La Source is best if you want to watch the opening meters after the start and plenty of braking action, while Pouhon and Blanchimont are better for understanding how the cars flow at full speed.', 'Bring a waterproof jacket and spare socks in a separate bag, because Spa can be dry at the parking lot while the area where you stand all afternoon is cold and soaked.', 'If you are arriving from Verviers-Central by public transport, remember that bus lines 294 and 395 operate differently on Sunday compared to Friday and Saturday.', 'Do not underestimate the elevation changes between sectors, so if your ticket is for one side of the track, stay there and enjoy the support races instead of constantly chasing another corner.', 'If you park at Malmedy Expo, use the shuttle service to the Combes entrance and return the same way, because it is much more comfortable than walking along the roads through evening traffic.'] },
      travelAdvice: { title: 'Travel Advice', description: 'Spa is one of those races where logistics can become just as demanding as the weather forecast, so it is important to decide in advance whether you are relying on trains, shuttles, cars, or a combination of options. A good plan here means less stress on the narrow Ardennes roads and far more energy for the circuit itself.', tips: ['Spa and Stavelot are the most practical places to stay if you want atmosphere, while Verviers and Liège work better if rail access and a larger hotel selection matter more to you.', 'The closest major train station is Verviers-Central, and the Event Train Ticket often gives discounted return travel from anywhere in Belgium when combined with your Grand Prix ticket code.', 'Public bus lines 294 and 395 from Verviers cost around 3.50 euros per ride, but do not rely on them for your Sunday return without checking the replacement shuttle system first.', 'If you are driving and want the lowest risk of mud problems, choose the Malmedy Expo asphalt parking with shuttle service instead of grassy parking fields near the village.', 'The park-and-ride bicycle option using the RAVeL route from the free parking area five kilometers from the circuit is excellent if you want to avoid the worst traffic entering and leaving the venue.', 'Pack hiking shoes or at least trainers with strong grip, because Spa is not the kind of circuit where smooth city sneakers feel comfortable on wet grassy slopes.'] },
    },
    hotels: [
      { name: 'Hotel de la Source', address: 'Route du Circuit 22, B-4970 Francorchamps, Belgium', lat: 50.4477129, lng: 5.9597799 },
      { name: 'Van der Valk Hotel Spa', address: 'Place Royale 39, 4900 Spa, Belgium', lat: 50.4925, lng: 5.865 },
      { name: 'Silva Hotel Spa-Balmoral', address: 'Route de Balmoral 33, 4900 Spa, Belgium', lat: 50.4784, lng: 5.887 },
    ],
  },
  {
    slug: 'italy', title: 'Italian Grand Prix', country: 'Italy', city: 'Monza',
    circuit: 'Autodromo Nazionale Monza',
    coordinates: { lat: 45.6156, lng: 9.2811 },
    weather: { location: 'Monza, Italy' },
    circuitInfo: { laps: 53, length_km: 5.793, drs_zones: 2, first_gp: 1950 },
    guideSections: {
      beforeRace: { title: 'Before the Race', description: 'Monza is special because it is not only about race day, but an entire weekend inside a massive royal park where motorsport and northern Italian city life blend together perfectly. If you plan your trip well, you can use Monza itself as a relaxed base before the tifosi transform the circuit into a full festival atmosphere.', tips: ['Spend a few hours in Parco di Monza and around Villa Reale before the main crowds arrive, because only then do you realize how huge the park really is before walking through it all weekend.', 'Have lunch in Monza\'s historic center around Via Bergamo or Piazza Trento e Trieste instead of planning every meal in Milan, because the town develops its own unique rhythm during Grand Prix weekend.', 'If you are arriving from Milan by train, do a practice run to Monza station and find the Black Shuttle departure point in advance so race day feels much less chaotic.', 'If you are in town a few days early and the Autodromo offers tours, take the one that includes the old banking and the Fangio statue, because it is one of the best historical additions to the entire weekend.', 'Wear comfortable shoes from Thursday onward, because Monza looks manageable on the map but the distances between stations, shuttles, gates, and grandstands become exhausting very quickly.', 'Buy water and basic supplies in town before heading into the park, because even the simplest purchase turns into another long queue on race day.'] },
      duringRace: { title: 'During the Race', description: 'Monza is pure speed, noise, and tifosi reacting to every moment as if it decides the championship itself. The track may look simple on television, but standing beside the fence shows how aggressively the cars attack Rettifilo, Lesmo, and Ascari with almost no margin for error.', tips: ['Arrive early because public entrances usually open around 7:30 on Friday and 7:00 on Saturday and Sunday, making the first morning hour the easiest way to avoid the worst congestion.', 'If your priority is the opening lap and heavy braking, focus on Rettifilo and Curva Grande, while Lesmo and Ascari are better for watching drivers flow through long sequences of direction changes.', 'The Black Shuttle saves energy getting into the park, but remember that you still face a serious walk from the drop-off area to the actual gates and grandstands.', 'Security checks can be strict with bottles and equipment, so bring a small plastic bottle under 500 ml and avoid carrying oversized power banks or metal containers without checking the rules first.', 'If you are meeting friends, the Fangio statue and Monza Circuit Shop are much smarter meeting points than random fence sections because everyone can find them easily.', 'When leaving the circuit, return through the same gate you entered from, whether it is Gate A Vedano, Gate B Santa Maria delle Selve, or the northern Biassono entrances, because crossing the park after the race takes forever.'] },
      travelAdvice: { title: 'Travel Advice', description: 'For most visitors it makes more sense to stay in Milan and travel to Monza by train, because you gain better nightlife, more restaurants, and a much larger range of hotels. Monza itself is excellent if you want shorter transfers, but the key is understanding which side of the park you need to access.', tips: ['Milano Centrale, Porta Garibaldi, and Isola are extremely practical bases, because Trenord trains connect Milan and Monza quickly without making you feel disconnected from the city.', 'If your grandstand is on the southern or eastern side of the track, plan your access through Vedano and Gates A or B, while the northern side works better from Biassono and Gates C, D, or E.', 'Taxis rarely drop you as close to the circuit as you expect, so the train plus shuttle or train plus walking combination is usually less stressful.', 'Download the Monza Circuit app and save the parking map from monzamobilita.it before your trip, because parking colors, shuttle routes, and entry systems are easier to manage when available offline.', 'If you stay in Monza itself, choose accommodation between the station and the historic center so you can handle both morning departures and evening dinners without unnecessary transfers.', 'For rainy days inside the park, pack a light rain jacket instead of a large umbrella, because oversized items are exactly what slows security checks at the entrances.'] },
    },
    hotels: [
      { name: 'Hotel de la Ville Monza', address: 'Viale Regina Margherita di Savoia 15, 20900 Monza, Italy', lat: 45.59262, lng: 9.27145 },
      { name: 'Helios Hotel Monza', address: 'Viale Elvezia 4, 20900 Monza, Italy', lat: 45.5958, lng: 9.2825 },
      { name: 'B&B Hotel Milano-Monza', address: 'Via Lario 19, 20900 Monza, Italy', lat: 45.59013, lng: 9.282 },
    ],
  },
  {
    slug: 'singapore', title: 'Singapore Grand Prix', country: 'Singapore', city: 'Singapore',
    circuit: 'Marina Bay Street Circuit',
    coordinates: { lat: 1.2914, lng: 103.8644 },
    weather: { location: 'Singapore' },
    circuitInfo: { laps: 62, length_km: 4.94, drs_zones: 3, first_gp: 2008 },
    guideSections: {
      beforeRace: { title: 'Before the Race', description: 'Singapore gives you the rare chance to experience a Grand Prix inside a city that already feels like part of the show long before the race begins. Marina Bay, the colonial Padang area, hawker centers, and compact neighborhoods make it easy to move around quickly and enjoy the city without exhausting yourself before race weekend.', tips: ['Walk around Marina Bay during daylight from Esplanade across Helix Bridge to the Singapore Flyer so you can understand the actual gate locations and distances between zones before the crowds arrive.', 'Eat at least one proper hawker meal at Maxwell Food Centre on Kadayanallur Street before switching to expensive race-week habits around the bay area.', 'If you want a neighborhood with real character before the evening sessions, spend a few hours in Kampong Glam around Arab Street and Haji Lane before returning toward the circuit.', 'For one of the best free city and track views, stand near Jubilee Bridge or the Fullerton area during blue hour just before sunset.', 'Use the air-conditioned walkways inside Marina Square, Suntec City, and Raffles City whenever heavy rain approaches, because it saves both time and energy in Singapore\'s humidity.', 'Pack a small fan, electrolyte drinks, and a thin poncho inside a zip bag, because Formula 1 in Singapore may happen at night but the humidity still feels intense.'] },
      duringRace: { title: 'During the Race', description: 'Singapore is one of the easier races logistically if you understand your zone and which gate actually belongs to your ticket. The biggest mistake is assuming everything is only a few minutes apart, because underground walkways, checkpoints, and huge crowds completely control the pace of the evening.', tips: ['Match your gate to your ticket properly: Gate 1 Republic Boulevard works best for Nicoll Highway, Gate 2 Temasek Avenue for Promenade, Gates 3A and 3B for City Hall and Esplanade, and Gate 8 for Helix and Bayfront.', 'If you have Raffles Grandstand tickets, use the advantage of full-zone access and avoid spending the entire evening in one place without exploring the circuit atmosphere.', 'For Zone 4 Walkabout tickets, Gates 3B, 4, 5, 6, and 7 are the most practical, so do not waste time trying to enter near the pit straight if your ticket does not allow it anyway.', 'Avoid changing zones immediately after a major session or concert, because the underground passages become extremely crowded and the move usually takes much longer than expected.', 'Light trainers and clothes that dry quickly matter far more than fashion, because you will spend hours dealing with humidity, sweat, and likely short rain showers.', 'After leaving the circuit, it is often faster to walk toward City Hall or Raffles Place instead of forcing yourself onto the first packed train at Promenade station.'] },
      travelAdvice: { title: 'Travel Advice', description: 'Singapore rewards accommodation near good MRT connections far more than hotels chosen only for luxury views. If you stay around City Hall, Bugis, Promenade, or even slightly farther away on a good MRT line, reaching the circuit becomes easier than for many people staying in expensive hotels without practical transport access.', tips: ['The most practical areas are City Hall, Bugis, and Promenade if you want to walk to the circuit, while Chinatown and Tiong Bahru offer a better balance of price and convenience for longer stays.', 'Use the MRT with a bank card or stored transit card, because even short ticket machine queues become frustrating during race weekend.', 'If you stay near Nicoll Highway or Bugis, walking to your gate is often smarter than taking a short taxi ride that gets trapped in road closures around the circuit.', 'Plan dinner after practice sessions around Beach Road, Boat Quay, or Circular Road, because those areas stay lively long after the food options inside the circuit begin losing quality.', 'Pack a quick-dry shirt, blister patches, and a lightweight poncho, because Singapore tests heat and humidity far more than complicated transport logistics.', 'If you stay outside the city center, check the extended MRT operating hours during race weekend and keep Grab as a backup after concerts, because crowd waves become unpredictable late at night.'] },
    },
    hotels: [
      { name: 'Mandarin Oriental, Singapore', address: '5 Raffles Avenue, Singapore 039797', lat: 1.287633, lng: 103.854897 },
      { name: 'Pan Pacific Singapore', address: '7 Raffles Boulevard, Marina Square, Singapore 039595', lat: 1.291533, lng: 103.859267 },
      { name: 'PARKROYAL COLLECTION Marina Bay', address: '6 Raffles Boulevard, Singapore 039594', lat: 1.291667, lng: 103.856667 },
    ],
  },
  {
    slug: 'azerbaijan', title: 'Azerbaijan Grand Prix', country: 'Azerbaijan', city: 'Baku',
    circuit: 'Baku City Circuit',
    coordinates: { lat: 40.3725, lng: 49.8533 },
    weather: { location: 'Baku, Azerbaijan' },
    circuitInfo: { laps: 51, length_km: 6.003, drs_zones: 2, first_gp: 2017 },
    guideSections: {
      beforeRace: { title: 'Before the Race', description: 'Baku combines one of the fastest modern street circuits with a city best experienced on foot between the Caspian waterfront, ancient stone walls, and elegant oil-era boulevards. Arriving a little earlier is worth it here, because learning the layout of the city center makes race weekend navigation far easier.', tips: ['Walk along Baku Boulevard from Port Baku Mall toward Park Bulvar in the evening, because it immediately shows you how long the main straight really is and where the widest waterfront spaces open up.', 'Visit Icherisheher and the Maiden Tower early in the morning before the larger crowds arrive, because the Old City sits directly beside the circuit and feels much calmer before tour groups appear.', 'For coffee, dinner, or simply a good city atmosphere, focus on Fountain Square and Nizami Street, because those areas remain practical both before and after the race sessions.', 'If you want panoramic views over the city and the bay, take the funicular from Neftchilar Avenue toward the upper viewpoints before the road closures become heavier.', 'Handle cash withdrawals, SIM cards, and small essentials around 28 May or Sahil before heading toward the circuit, because it is much easier than dealing with those tasks between checkpoints.', 'The day before the race, walk between Port Baku, Park Bulvar, and Azneft Square so you understand where your entrances and possible exits are located within the city layout.'] },
      duringRace: { title: 'During the Race', description: 'Baku is a race with two completely different personalities: one side is the enormous flat-out straight beside the sea, while the other is the narrow castle section where the cars seem barely wide enough to fit between the walls. That means choosing a sector is more about personal preference than pure overtaking statistics.', tips: ['The easiest access comes through the metro stations at 28 May, Sahil, or Icheri Sheher, because those stops naturally distribute spectators around the major circuit entrances.', 'If your tickets are near the pit straight or waterfront sectors, entering from the Port Baku side is usually easier than pushing through the denser crowds near the Old City.', 'For the most unique circuit atmosphere, focus on the Castle section and Giz Galasi area, but make sure you have a good screen view because much of the action there is followed through sound and live timing.', 'Remember bus numbers 65, 5, and 53, because they handle a large part of central city transport once special traffic rules begin during race weekend.', 'If you stay for concerts at Crystal Hall, either use the official shuttle near the Giz Galasi sectors or enjoy the roughly 2.5 kilometer walk along the boulevard if the weather is pleasant.', 'After 10 p.m., follow the marked exits toward 28 May, Sahil, or Icheri Sheher instead of waiting around the main gates that often close earlier than expected.'] },
      travelAdvice: { title: 'Travel Advice', description: 'Baku is one of the few newer Formula 1 races where staying directly in the city center is genuinely worth it, because the circuit, promenade, restaurants, and metro are all within comfortable distances. Choosing the right neighborhood can easily cut your need for taxis in half.', tips: ['The most practical areas are Sahil and the surroundings of Nizami Street for nightlife, the Old City for atmosphere, and 28 May for transport connections across the rest of Baku.', 'Choose your hotel based on which side of the circuit you expect to enter most often, because Port Baku works better for the pit straight while Icheri Sheher is ideal for the castle section.', 'Baku is very walkable along Neftchilar Avenue and the boulevard, but the steep and slippery stone streets inside Icherisheher require better footwear than most tourists normally pack.', 'Evenings beside the Caspian Sea can become surprisingly windy, so bring a light jacket even if the daytime weather feels warm and calm.', 'If you are arriving by plane, organize your transfer into the city center in advance instead of improvising after midnight, because the combination of luggage and road closures can make the city feel more complicated than it actually is.', 'Keep a copy of your passport separate from your main wallet and stay organized with your belongings, because race weekend involves repeated checkpoints and controlled pedestrian corridors.'] },
    },
    hotels: [
      { name: 'Hilton Baku', address: '1B Azadliq Avenue, Baku AZ1000, Azerbaijan', lat: 40.371944, lng: 49.849444 },
      { name: 'JW Marriott Absheron Baku', address: '674 Azadliq Square, Baku AZ1010, Azerbaijan', lat: 40.37417, lng: 49.85639 },
      { name: 'Promenade Hotel Baku', address: '9-13 Neftchilar Avenue, Baku, Azerbaijan', lat: 40.3663, lng: 49.836 },
    ],
  },
  {
    slug: 'usa', title: 'United States Grand Prix', country: 'USA', city: 'Austin',
    circuit: 'Circuit of the Americas',
    coordinates: { lat: 30.1328, lng: -97.6411 },
    weather: { location: 'Austin, Texas' },
    circuitInfo: { laps: 56, length_km: 5.513, drs_zones: 2, first_gp: 2012 },
    guideSections: {
      beforeRace: { title: 'Before the Race', description: 'Austin works best when you treat the Grand Prix as more than just a circuit visit and combine it with live music, tacos, and time around the city itself. COTA sits outside downtown, but the city side of the weekend gives the entire American race a personality you immediately feel once you walk through South Congress or East Austin.', tips: ['Spend a morning on South Congress Avenue before cooling off at Barton Springs Pool inside Zilker Park, because it is one of the best ways to escape the Texas heat before heading to the circuit.', 'For food before the race sessions, explore East Austin around East 6th Street or East Cesar Chavez, where the atmosphere feels far more local than the convention-center tourist areas.', 'If you plan to use the official shuttle service, confirm the exact departure point the day before and save the map on your phone, because race morning is not the time to search for buses among thousands of people and temporary road diversions.', 'If you are driving, fuel up and buy everything you need before turning toward Del Valle, because the areas around FM-812 and Elroy Road become heavily congested very quickly.', 'Check your parking lot assignment before the weekend begins, because Lots A, N, and T use different access routes from Lots C, D, E, F, G, H, and K, and the same navigation route can easily send you to the wrong side of the venue.', 'Buy sunscreen, sunglasses, and extra water inside Austin before race weekend, because the relaxed city atmosphere can make you forget how intense the Texas sun feels at COTA the next day.'] },
      duringRace: { title: 'During the Race', description: 'COTA is a circuit where it really helps to know what you want to watch, because one side of the experience is the dramatic uphill start into Turn 1 while another is the technical rhythm through the esses and heavy braking at Turn 12. The venue is enormous, so a planned day feels far more enjoyable than wandering without direction.', tips: ['Arrive early at Turn 1 if you want the most iconic start view of the weekend, because the steep hill and wide track layout feel much more dramatic in person.', 'For pure car rhythm and direction changes, Turns 3 through 6 are the best sections, but bring binoculars or accept that you are watching flowing lines rather than classic overtaking battles.', 'If heavy braking action matters most to you, Turn 12 is the strongest choice, while the area around Turn 15 and the stadium section gives you several different viewing angles in one place.', 'From McAngus Lot, use the official tram service toward Grand Plaza instead of walking all the way from the rideshare area, because the distance becomes exhausting faster than most people expect.', 'The biggest Texas mistake is underestimating the midday sun before the main race, so refill water and find shade before the crowd settles into place for the start.', 'If you do not need to leave immediately, stay for the concert or at least let the first departure wave pass, because shuttle and rideshare lines explode right after the checkered flag.'] },
      travelAdvice: { title: 'Travel Advice', description: 'For the United States Grand Prix, it almost always makes more sense to stay where you have restaurants and nightlife and then travel to the circuit with a proper plan instead of trying to stay as close to COTA as possible. Downtown Austin, East Austin, and areas near the airport usually provide the smartest balance.', tips: ['Downtown Austin, East Austin, and South Congress are the best bases if you want to combine the race with music, food, and a good selection of bars and cafés after returning from the circuit.', 'Hotels near the airport may shorten the morning drive, but without a car they often become less practical than staying downtown with a reliable shuttle plan.', 'If you are driving from Austin or Dallas, some parking lots work best via TX-130 South and Exit 451 toward Elroy Road, while other areas use Exit 453 toward FM-812.', 'If you are arriving from Houston or Bastrop, routes through Kellam Road or Ross Road are often easier than trying to cut through central Austin traffic.', 'For rideshare or private drop-offs, tell your driver to head specifically to McAngus Lot instead of simply saying COTA, because that can be the difference between an organized arrival and getting stranded on the wrong side of the perimeter.', 'Pack layers even if the weather forecast looks warm, because Texas mornings in October or November can feel cool while the afternoon becomes intensely sunny.'] },
    },
    hotels: [
      { name: 'Hyatt Place Austin Airport', address: '9532 Spirit of Austin Ln, Austin, TX 78719, USA', lat: 30.2045, lng: -97.666 },
      { name: 'Hilton Austin Airport', address: '9515 Hotel Dr, Austin, TX 78719, USA', lat: 30.2028, lng: -97.6628 },
      { name: 'Cambria Hotel Austin Airport', address: '7800 E Ben White Blvd, Austin, TX 78741, USA', lat: 30.2205, lng: -97.6937 },
    ],
  },
  {
    slug: 'brazil', title: 'Brazilian Grand Prix', country: 'Brazil', city: 'Sao Paulo',
    circuit: 'Interlagos',
    coordinates: { lat: -23.7036, lng: -46.6997 },
    weather: { location: 'Sao Paulo, Brazil' },
    circuitInfo: { laps: 71, length_km: 4.309, drs_zones: 2, first_gp: 1973 },
    guideSections: {
      beforeRace: { title: 'Before the Race', description: 'Interlagos is a racing cathedral, but a successful trip to São Paulo actually depends a lot on the neighborhoods far away from the circuit that help you manage the scale of the city. Before race weekend, it is worth experiencing Paulista Avenue, Jardins, and Pinheiros first before shifting your focus toward the southern side of the city and pure motorsport.', tips: ['Spend your first days around Avenida Paulista and the nearby streets of Jardins, because that area balances museums, food, metro access, and a more comfortable urban atmosphere.', 'For lunch or dinner, head toward Rua dos Pinheiros or Mercado de Pinheiros, where it is easier to eat well and quickly than in the more chaotic tourist-heavy central areas.', 'If you want a quieter city break before Interlagos, visit Parque Trianon or take a short walk through Jardim Paulista before spending entire days on your feet at the circuit.', 'Do a practice run on Line 9 and learn the transfers between Pinheiros, Morumbi, Autódromo, or Cidade Dutra stations the day before the race, because the real weekend becomes much easier once you already know the system.', 'Avoid carrying unnecessary valuables while exploring the city at night and use ride-hailing apps for late returns, especially if you are coming back from distant neighborhoods after dinner.', 'Buy a rain jacket and cap in the city before race weekend, because Interlagos loves combining heat, wind, and sudden rain showers in the same afternoon.'] },
      duringRace: { title: 'During the Race', description: 'Interlagos has the kind of atmosphere that makes everything feel louder, steeper, and more emotional than almost anywhere else on the calendar. From the downhill charge through Senna S to the exit of Junção, nearly every sector rewards patience and a carefully chosen viewing spot.', tips: ['If your goal is the most emotional race view possible, nothing beats the start and opening lap through Senna S and Curva do Sol, so arrive earlier than you think is necessary.', 'For a more technical feeling of the circuit, the areas around Mergulho and Junção are excellent because they show how uneven and physically demanding Interlagos really is.', 'Use the GPSP Express to Cidade Dutra or the regular Line 9 toward Autódromo station, then follow the official police-guided corridors and signage instead of improvising through side streets.', 'If you exit at Autódromo station, remember that shuttle buses connect to the main entrances but not directly to Gate G and the fan zone, so walking can sometimes be faster.', 'Grandstands without catering packages still provide free water refill points, so it is worth organizing a cup or light bottle early instead of waiting for the hottest part of the day.', 'After the race, stay with the main crowd flow back toward Line 9 and avoid trying shortcuts along Avenida Senador Teotônio Vilela, especially if you are alone.'] },
      travelAdvice: { title: 'Travel Advice', description: 'São Paulo is a city where the neighborhood you choose matters more than the actual distance to the circuit. If you choose the right base and transport strategy, Interlagos feels manageable, but a poor setup can easily cost you hours in traffic and difficult transfers.', tips: ['The most practical neighborhoods for most visitors are Jardins, Paulista, Pinheiros, and Itaim Bibi, because they offer strong restaurant options and relatively manageable journeys toward the southern side of the city.', 'Do not rely on parking at the circuit, because Interlagos does not provide normal public spectator parking during Grand Prix weekend and a private car often creates more problems than solutions.', 'The GPSP Express train departs from Pinheiros, stops at Morumbi, and then runs directly toward Cidade Dutra, skipping the slowest section of the regular race-day approach.', 'If you prefer buses, look for SPTrans Express departures from places such as SP Market, Congonhas near Praça Comandante Lineu Gomes, Trianon-MASP, or Terminal Santo Amaro.', 'During major station transfers, keep your phone and wallet closer to your body than you might in a smaller city, because race weekend creates extremely crowded platforms and exits.', 'Even if you stay relatively close to the southern districts, leave yourself a large time buffer on Friday afternoons and Sunday evenings because Marginal Pinheiros and the approaches to Interlagos become heavily congested.'] },
    },
    hotels: [
      { name: 'ibis Sao Paulo Interlagos', address: 'Av. Interlagos 2215, São Paulo - SP, 04661-200, Brazil', lat: -23.67297, lng: -46.67702 },
      { name: 'Transamerica Executive Chácara Santo Antônio', address: 'Rua Américo Brasiliense 2163, São Paulo - SP, 04715-005, Brazil', lat: -23.6298, lng: -46.7042 },
      { name: 'Blue Tree Premium Verbo Divino', address: 'Rua Verbo Divino 1323, São Paulo - SP, 04719-002, Brazil', lat: -23.633, lng: -46.7048 },
    ],
  },
  {
    slug: 'las-vegas', title: 'Las Vegas Grand Prix', country: 'USA', city: 'Las Vegas',
    circuit: 'Las Vegas Strip Circuit',
    coordinates: { lat: 36.1147, lng: -115.1728 },
    weather: { location: 'Las Vegas, Nevada' },
    circuitInfo: { laps: 50, length_km: 6.201, drs_zones: 2, first_gp: 2023 },
    guideSections: {
      beforeRace: { title: 'Before the Race', description: 'The Las Vegas Grand Prix becomes much easier once you treat it like a logistical puzzle between resorts, pedestrian bridges, the monorail, and a few important walking corridors. The city itself already feels like a spectacle, but the best weekends belong to the people who learn how to move efficiently between the Sphere, the Strip, and the eastern resort areas before the crowds arrive.', tips: ['Walk part of Las Vegas Boulevard during the daytime between Bellagio, Caesars Palace, Venetian, and the Sphere, because everything feels completely different once the nighttime crowds and race-week road closures begin.', 'For a calmer start to the evening, visit the Arts District around Main Street and Charleston Boulevard before heading toward the Strip once race-week traffic settles slightly.', 'If you want to experience a more local and older side of Las Vegas during a free evening, spend time around Fremont East and Fremont Street Experience instead of using your entire budget on expensive drinks near the circuit.', 'Buy a monorail pass in advance and remember the correct station for your zone: Harrah\'s-The LINQ for the Sphere area, Flamingo-Caesars for the central Strip, and Horseshoe-Paris for Harmon and Koval sectors.', 'Take time to visit Grand Prix Plaza before the official race weekend begins, because it helps you understand how the entire event is organized across the resort areas and walking routes.', 'Pack a light jacket during the afternoon already, because desert nights on open grandstands feel much colder than walking through warm hotel corridors.'] },
      duringRace: { title: 'During the Race', description: 'Las Vegas may look compact on the map, but race weekend transforms a few city blocks into a serious test of patience and planning. The biggest advantage is not only having a good ticket but also understanding which bridge, station, or parallel street actually gets you back to your hotel efficiently.', tips: ['Use the pedestrian bridges around Flamingo Road, Paris-Horseshoe, and the walkways near Venetian and Sands Avenue, because searching for street-level crossings at the wrong time only wastes energy.', 'The Sphere zone offers the most recognizable race views, but Harmon and Koval sectors are often easier to navigate once you are inside the venue.', 'Buy coffee, water, or a simple meal inside your resort before entering the race areas, because the first post-security rush creates much longer queues than most people expect.', 'The Las Vegas Monorail avoids all major road closures, so after sessions it is almost always faster to exit through MGM Grand, Horseshoe-Paris, Flamingo-Caesars, or Harrah\'s-The LINQ stations than relying on rideshares immediately.', 'Do not underestimate how cold it feels standing outside after 10 p.m., because the desert air quickly affects your hands and legs even after a warm day.', 'If you order transportation after the race, walk several blocks toward Paradise Road or Sands Avenue before requesting the ride, because pickups directly beside the circuit are the slowest and most expensive.'] },
      travelAdvice: { title: 'Travel Advice', description: 'During the Las Vegas Grand Prix, your location relative to the monorail and pedestrian bridges matters much more than how glamorous your hotel looks online. A famous resort with poor access can become far less practical than a simpler hotel positioned on the correct side of the race-week chaos.', tips: ['If easy transport matters most, choose hotels near MGM Grand, Horseshoe-Paris, Flamingo-Caesars, or Harrah\'s-The LINQ, because those are the most useful monorail access points during race weekend.', 'Downtown accommodation near Fremont Street can save money, but expect additional transfers toward the monorail or direct rideshare trips before the full road closures begin.', 'The Las Vegas Monorail runs through seven stations from MGM Grand to SAHARA and becomes the single most useful tool once Las Vegas Boulevard stops functioning like a normal road.', 'Buy your monorail pass online before arriving and use your phone as the ticket, because physical ticket purchases at stations become frustrating exactly when the crowds are largest.', 'If you rent a car, leave it parked for the entire weekend, because Koval Lane, Harmon Avenue, and Sands Avenue are exactly the kind of places where race-week traffic completely collapses.', 'November in Las Vegas is dry and surprisingly draining, so alongside your jacket pack lip balm, water, and a power bank in the same small bag.'] },
    },
    hotels: [
      { name: 'The Venetian Resort', address: '3355 S Las Vegas Blvd, Las Vegas, NV 89109, USA', lat: 36.12139, lng: -115.16889 },
      { name: 'Bellagio', address: '3600 S Las Vegas Blvd, Las Vegas, NV 89109, USA', lat: 36.112625, lng: -115.176704 },
      { name: 'Paris Las Vegas', address: '3655 S Las Vegas Blvd, Las Vegas, NV 89109, USA', lat: 36.112541, lng: -115.17067 },
    ],
  },
  {
    slug: 'uae', title: 'Abu Dhabi Grand Prix', country: 'UAE', city: 'Abu Dhabi',
    circuit: 'Yas Marina Circuit',
    coordinates: { lat: 24.4672, lng: 54.6031 },
    weather: { location: 'Abu Dhabi, UAE' },
    circuitInfo: { laps: 58, length_km: 5.281, drs_zones: 2, first_gp: 2009 },
    guideSections: {
      beforeRace: { title: 'Before the Race', description: 'The Abu Dhabi finale feels different from most races on the calendar because Yas Island is not only home to the circuit but an entire entertainment district filled with marinas, concerts, resorts, and theme parks. If you arrive a little earlier, this becomes one of the easiest Formula 1 weekends to enjoy without the stress of a massive city commute.', tips: ['Before race weekend begins, walk around Yas Marina, Yas Bay Waterfront, and Yas Mall, because those three locations become the most useful reference points for navigating the island.', 'Use the free Yas Island hop-on shuttle service before the crowds arrive so you understand the layout of the island and the distances between attractions and race entrances.', 'If Yas Marina Circuit offers a pre-weekend track tour or driving experience, book it early because it makes understanding the grandstand layout and entry routes much easier once race weekend begins.', 'Reserve dinner at Yas Bay Waterfront instead of relying only on hotel restaurants, because that area develops a much stronger atmosphere during the evenings.', 'Ferrari World and SeaWorld are genuinely practical additions to this trip because they sit only minutes away from the circuit and do not require major city transfers.', 'Even though December is far more comfortable than the summer months, keep sunscreen and a light evening layer in your bag because the marina breeze becomes noticeable after sunset.'] },
      duringRace: { title: 'During the Race', description: 'Yas Marina Circuit is one of the cleanest and easiest venues to navigate on the calendar, but that also means it helps to decide what type of experience you actually want instead of randomly choosing a grandstand. The season finale is not only about the race itself but also about the flow toward the marina, fan zones, and concerts after the sessions end.', tips: ['North Grandstand is the strongest choice if you want to watch heavy braking at the end of the long straight, while West and South grandstands reward people who prefer seeing multiple corners in a single view.', 'For Yasalam concerts, begin moving toward the exits slightly before the main crowd or immediately after the race program ends, because the walkways between the circuit and concert areas become extremely congested very quickly.', 'Use the marked pedestrian bridges and island walkways instead of trying to order transport directly outside your gate, because the final ten minutes on foot are often the fastest part of the journey.', 'Buy food and drinks before the major break leading into Formula 1 sessions, because the busiest queues form exactly when the main fan movement begins.', 'If you sit near the marina or other open sectors, a light jacket after sunset is genuinely useful rather than optional, especially once the wind moves across the water.', 'If you are meeting friends after the race, choose a fixed point such as Yas Marina or the Yas Mall entrance because crowds and weak signal near the exits make improvisation difficult.'] },
      travelAdvice: { title: 'Travel Advice', description: 'The easiest Abu Dhabi plan is staying directly on Yas Island, but the race is still manageable from central Abu Dhabi or even Dubai if you organize your transport carefully. The key decision is how much convenience you want compared to how much city life you want outside the race itself.', tips: ['The simplest option is staying on Yas Island itself, but Saadiyat and central Abu Dhabi work better if you want more restaurants and a more normal city atmosphere outside the race.', 'For cheaper public transport access, use Bus 190 from Abu Dhabi Bus Station near Al Wahda Mall toward Yas Island because it is the clearest low-cost route to the circuit area.', 'If you are arriving from Dubai, first organize transport toward Abu Dhabi Bus Station and then transfer onto Bus 190 instead of improvising the entire journey in one step.', 'Taxis, Uber, and Careem operate well during race weekend, but for the return trip choose clear pickup points such as Yas Mall or Etihad Arena once the roads reopen.', 'If you are not staying on Yas Island, leave earlier than you think necessary, especially on Sunday, because traffic toward the island becomes heavy long before the support races finish.', 'Keep your tickets and QR codes saved inside the Abu Dhabi GP app and also store screenshots offline because you do not want to rely on mobile signal directly before the entrance checkpoints.'] },
    },
    hotels: [
      { name: 'W Abu Dhabi - Yas Island', address: 'Yas Island, Abu Dhabi, United Arab Emirates', lat: 24.4672, lng: 54.6031 },
      { name: 'Crowne Plaza Abu Dhabi - Yas Island', address: 'Yas Plaza Hotels, Yas Island, Abu Dhabi 41880, United Arab Emirates', lat: 24.4662, lng: 54.5985 },
      { name: 'Centro Yas Island', address: 'Yas Plaza, Yas Island, Abu Dhabi, United Arab Emirates', lat: 24.465173, lng: 54.598734 },
    ],
  },
]

async function seed() {
  await sequelize.authenticate()

  for (const g of guides) {
    await Guide.upsert({
      slug:             g.slug,
      title:            g.title,
      country:          g.country,
      city:             g.city,
      circuit:          g.circuit,
      lat:              g.coordinates.lat,
      lng:              g.coordinates.lng,
      weather_location: g.weather.location,
      circuit_info:     g.circuitInfo,
      guide_sections:   g.guideSections,
      hotels:           g.hotels,
    })
    console.log(`  ✓ ${g.slug}`)
  }

  console.log(`\nSeeded ${guides.length} guides.`)
  await sequelize.close()
}

seed().catch(err => {
  console.error(err)
  process.exit(1)
})
